"""Incremental lecture notes.

Every pass sends only the transcript added since the last pass to the text
provider, asks for structured Markdown sections, and merges the result into
the existing notes section by section. Without any model available, a
heuristic extractor keeps producing something rather than nothing.
"""

import logging
import re

import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from config import get_settings
from models import NotesVersion, Session, TranscriptSegment

logger = logging.getLogger(__name__)
settings = get_settings()

# Extracts structured points from a NEW transcript segment only.
# We deliberately do NOT pass existing notes here — keeping the prompt small
# and focused prevents the model from hallucinating or recycling old content.
EXTRACT_PROMPT_TEMPLATE = """You are a teaching assistant extracting key information from a lecture
transcript segment.

Transcript:
{transcript}

Extract ONLY information explicitly present in this transcript segment.
Return markdown with ONLY the sections that have relevant content — omit any section with
nothing to add.

## Key Concepts
- **[concept name]**: brief explanation

## Definitions
- **[term]**: definition as stated in the lecture

## Examples
- description of example given

## Action Items / Deadlines
- assignment, deadline, exam, or quiz mentioned

## Questions Raised
- question asked or raised for further study

Rules:
- Only include a section if the transcript has content for it
- Never invent or infer content not stated in the transcript
- Bullet points only, no prose paragraphs
- Be concise"""


# Windows processed in one pass when catching up on a backlog (each is one
# model call); anything beyond is picked up by the next pass.
MAX_BATCHES_PER_PASS = 8


async def check_ollama_available() -> bool:
    """``True`` if the local Ollama answers on its base URL."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(f"{settings.ollama_base_url}/api/tags")
            return response.status_code == 200
    except Exception:
        return False


OLLAMA_WINDOW_CHARS = 3000  # what the local model can digest per call (num_ctx 8192)
CLOUD_WINDOW_CHARS = 24_000


async def extract_notes(transcript: str) -> str | None:
    """Extract notes for one transcript window with the configured provider.

    If a cloud provider fails and the call falls back to local Ollama, a
    cloud-sized window is far more than Ollama can read, so it is re-run in
    Ollama-sized slices and the results merged — nothing is silently skimmed.
    """
    from providers import generate_text

    try:
        result = await generate_text(
            EXTRACT_PROMPT_TEMPLATE.format(transcript=transcript),
            max_tokens=800,
            temperature=0.1,
            timeout=120.0,
        )
    except Exception as e:
        logger.error(f"Notes generation failed: {e}")
        return None
    logger.info("Notes generated by %s", result.provider)

    if result.provider.startswith("ollama/") and len(transcript) > OLLAMA_WINDOW_CHARS * 1.5:
        logger.info("Re-running a %d-char window in local-sized slices", len(transcript))
        merged = ""
        for i in range(0, len(transcript), OLLAMA_WINDOW_CHARS):
            piece = await extract_notes(transcript[i : i + OLLAMA_WINDOW_CHARS])
            if piece:
                merged = merge_notes(merged, piece)
        return merged or result.text
    return result.text


async def extract_notes_with_ollama(transcript: str) -> str | None:
    """Backwards-compatible name for ``extract_notes``."""
    return await extract_notes(transcript)


def _bullet_key(line: str) -> str:
    """Normalised bullet text for duplicate detection."""
    return re.sub(r"\W+", " ", line.lower()).strip()


def _bullet_term(line: str) -> str | None:
    """The bold lead term of a definition-style bullet (``- **Term**: ...``)."""
    m = re.match(r"^\s*[-*•]\s*\*\*(.+?)\*\*\s*:", line)
    return m.group(1).strip().lower() if m else None


def merge_notes(existing: str, new_extraction: str) -> str:
    """
    Merge new extracted notes into existing notes by section.
    If existing notes already have a section, append new bullets under it.
    New sections are added at the end. Sections with no new content are preserved as-is.
    """
    if not new_extraction or not new_extraction.strip():
        return existing

    section_re = re.compile(r"^(#{1,3}\s+.+)$", re.MULTILINE)

    def parse_sections(text: str) -> dict[str, list[str]]:
        """Returns {heading: [bullet lines]} preserving order via insertion."""
        result: dict[str, list[str]] = {}
        current_heading = "__preamble__"
        for line in text.splitlines():
            if section_re.match(line):
                current_heading = line.strip()
                if current_heading not in result:
                    result[current_heading] = []
            else:
                result.setdefault(current_heading, []).append(line)
        return result

    existing_sections = parse_sections(existing) if existing else {}
    new_sections = parse_sections(new_extraction)

    # Merge: for each section in new_extraction, append its bullets to existing
    for heading, lines in new_sections.items():
        if heading == "__preamble__":
            continue
        new_bullets = [line for line in lines if line.strip()]
        if not new_bullets:
            continue
        if heading in existing_sections:
            # Skip bullets already present: an exact repeat, or a "**Term**:"
            # definition whose term is already defined in this section.
            existing = existing_sections[heading]
            seen_text = {_bullet_key(line) for line in existing}
            seen_terms = {t for t in (_bullet_term(line) for line in existing) if t}
            fresh = []
            for line in new_bullets:
                term = _bullet_term(line)
                if _bullet_key(line) in seen_text or (term and term in seen_terms):
                    continue
                fresh.append(line)
                seen_text.add(_bullet_key(line))
                if term:
                    seen_terms.add(term)
            if fresh:
                existing.extend([""] + fresh)
        else:
            existing_sections[heading] = new_bullets

    # Reconstruct markdown
    parts = []
    for heading, lines in existing_sections.items():
        if heading == "__preamble__":
            preamble = "\n".join(lines).strip()
            if preamble:
                parts.append(preamble)
            continue
        content = "\n".join(lines).strip()
        if content:
            parts.append(f"{heading}\n{content}")
        else:
            parts.append(heading)

    return "\n\n".join(parts)


def extract_heuristic_notes(transcript: str) -> str:
    """Simple pattern-based extraction as fallback when Ollama is unavailable."""
    sections: dict[str, list[str]] = {
        "## Key Concepts": [],
        "## Definitions": [],
        "## Examples": [],
        "## Action Items / Deadlines": [],
        "## Questions Raised": [],
    }

    sentences = [s.strip() for s in re.split(r"[.!?]+", transcript) if len(s.strip()) > 15]

    for sentence in sentences:
        sl = sentence.lower()
        if re.search(r"\b(is defined as|means|refers to|is called)\b", sl):
            sections["## Definitions"].append(f"- {sentence}")
        elif re.search(r"\b(for example|such as|for instance|e\.g\.)\b", sl):
            sections["## Examples"].append(f"- {sentence}")
        elif re.search(r"\b(assignment|homework|due|deadline|exam|quiz|submit)\b", sl):
            sections["## Action Items / Deadlines"].append(f"- {sentence}")
        elif re.search(r"\b(why|how does|what is|when does)\b.*\?", sl):
            sections["## Questions Raised"].append(f"- {sentence}")

    parts = []
    for heading, bullets in sections.items():
        if bullets:
            parts.append(f"{heading}\n" + "\n".join(bullets[:8]))

    return "\n\n".join(parts)


async def generate_notes_for_session(
    db: AsyncSession,
    session_id: str,
    broadcast_callback=None,
) -> NotesVersion | None:
    """Run one notes pass for a session and store it as a new version.

    Reads segments newer than ``last_summarized_segment_id``, extracts notes
    from that window, merges them into the previous version, saves the
    result and (optionally) broadcasts it to the browser. Returns the new
    ``NotesVersion`` or ``None`` when there was nothing new.
    """
    session_result = await db.execute(select(Session).where(Session.id == session_id))
    session = session_result.scalar_one_or_none()
    if not session:
        logger.warning(f"Session {session_id} not found")
        return None

    query = select(TranscriptSegment).where(TranscriptSegment.session_id == session_id)
    if session.last_summarized_segment_id:
        last_segment_result = await db.execute(
            select(TranscriptSegment).where(
                TranscriptSegment.id == session.last_summarized_segment_id
            )
        )
        last_segment = last_segment_result.scalar_one_or_none()
        if last_segment:
            query = query.where(TranscriptSegment.created_at > last_segment.created_at)

    query = query.order_by(TranscriptSegment.chunk_index, TranscriptSegment.ts_start)
    segments_result = await db.execute(query)
    segments = segments_result.scalars().all()

    if not segments:
        logger.info(f"No new segments for session {session_id}")
        return None

    latest_notes_result = await db.execute(
        select(NotesVersion)
        .where(NotesVersion.session_id == session_id)
        .order_by(NotesVersion.version.desc())
        .limit(1)
    )
    latest_notes = latest_notes_result.scalar_one_or_none()
    current_notes = latest_notes.notes_md if latest_notes else ""

    # Which extractor can run. Cloud providers need no local model; Ollama
    # needs to be reachable, otherwise the heuristic extractor keeps notes
    # coming rather than producing nothing.
    from providers import active_provider

    provider = active_provider()
    use_model = provider != "ollama" or await check_ollama_available()
    if not use_model:
        logger.info(f"Ollama unavailable, using heuristics for session {session_id}")

    # A normal pass covers ~60 s of speech, but after a gap (a dropped socket
    # stops the loop until audio resumes) there can be an hour of backlog. Walk
    # it in windows the model can digest rather than truncating to the tail,
    # bounded per pass so a huge backlog is spread over successive passes.
    window_chars = OLLAMA_WINDOW_CHARS if provider == "ollama" else CLOUD_WINDOW_CHARS
    batches: list[list] = [[]]
    size = 0
    for seg in segments:
        if batches[-1] and size + len(seg.text) > window_chars:
            batches.append([])
            size = 0
        batches[-1].append(seg)
        size += len(seg.text) + 1
    batches = batches[:MAX_BATCHES_PER_PASS]
    if len(batches) > 1:
        logger.info(f"Session {session_id}: notes backlog, processing {len(batches)} windows")

    notes_md = current_notes
    for batch in batches:
        text = " ".join(seg.text for seg in batch)
        extracted = await extract_notes(text) if use_model else None
        notes_md = merge_notes(notes_md, extracted or extract_heuristic_notes(text))
    last_processed = batches[-1][-1]

    new_version = (latest_notes.version + 1) if latest_notes else 1

    notes_version = NotesVersion(
        session_id=session_id,
        version=new_version,
        notes_md=notes_md,
    )
    db.add(notes_version)

    session.last_notes_version = new_version
    session.last_summarized_segment_id = last_processed.id

    await db.commit()
    await db.refresh(notes_version)

    logger.info(f"Created notes version {new_version} for session {session_id}")

    if broadcast_callback:
        await broadcast_callback(
            session_id,
            {
                "type": "notes_update",
                "notes_md": notes_md,
                "version": new_version,
            },
        )

    return notes_version
