"""Incremental lecture notes.

Every pass sends only the transcript added since the last pass to the text
provider, asks for structured Markdown sections, and merges the result into
the existing notes section by section. Without any model available, a
heuristic extractor keeps producing something rather than nothing.
"""

import logging
import re

import httpx
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from config import get_settings
from models import NotesVersion, Session, TranscriptSegment

logger = logging.getLogger(__name__)
settings = get_settings()

# Extracts structured points from a NEW transcript segment only.
# We deliberately do NOT pass existing notes here — keeping the prompt small
# and focused prevents the model from hallucinating or recycling old content.
EXTRACT_PROMPT_TEMPLATE = """You are a teaching assistant extracting key information from a lecture
transcript segment.

Transcript:
{transcript}

Extract ONLY information explicitly present in this transcript segment.
Return markdown with ONLY the sections that have relevant content — omit any section with
nothing to add.

## Key Concepts
- **[concept name]**: brief explanation

## Definitions
- **[term]**: definition as stated in the lecture

## Examples
- description of example given

## Action Items / Deadlines
- assignment, deadline, exam, or quiz mentioned

## Questions Raised
- question asked or raised for further study

Rules:
- Only include a section if the transcript has content for it
- Never invent or infer content not stated in the transcript
- Bullet points only, no prose paragraphs
- Be concise"""


async def check_ollama_available() -> bool:
    """``True`` if the local Ollama answers on its base URL."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(f"{settings.ollama_base_url}/api/tags")
            return response.status_code == 200
    except Exception:
        return False


async def extract_notes_with_ollama(transcript: str) -> str | None:
    """Extract notes with the configured text provider (name kept for callers)."""
    from providers import generate_text

    prompt = EXTRACT_PROMPT_TEMPLATE.format(transcript=transcript)
    try:
        result = await generate_text(prompt, max_tokens=800, temperature=0.1, timeout=120.0)
        logger.info("Notes generated by %s", result.provider)
        return result.text
    except Exception as e:
        logger.error(f"Notes generation failed: {e}")
        return None


def merge_notes(existing: str, new_extraction: str) -> str:
    """
    Merge new extracted notes into existing notes by section.
    If existing notes already have a section, append new bullets under it.
    New sections are added at the end. Sections with no new content are preserved as-is.
    """
    if not new_extraction or not new_extraction.strip():
        return existing

    section_re = re.compile(r"^(#{1,3}\s+.+)$", re.MULTILINE)

    def parse_sections(text: str) -> dict[str, list[str]]:
        """Returns {heading: [bullet lines]} preserving order via insertion."""
        result: dict[str, list[str]] = {}
        current_heading = "__preamble__"
        for line in text.splitlines():
            if section_re.match(line):
                current_heading = line.strip()
                if current_heading not in result:
                    result[current_heading] = []
            else:
                result.setdefault(current_heading, []).append(line)
        return result

    existing_sections = parse_sections(existing) if existing else {}
    new_sections = parse_sections(new_extraction)

    # Merge: for each section in new_extraction, append its bullets to existing
    for heading, lines in new_sections.items():
        if heading == "__preamble__":
            continue
        new_bullets = [line for line in lines if line.strip()]
        if not new_bullets:
            continue
        if heading in existing_sections:
            existing_sections[heading].extend([""] + new_bullets)
        else:
            existing_sections[heading] = new_bullets

    # Reconstruct markdown
    parts = []
    for heading, lines in existing_sections.items():
        if heading == "__preamble__":
            preamble = "\n".join(lines).strip()
            if preamble:
                parts.append(preamble)
            continue
        content = "\n".join(lines).strip()
        if content:
            parts.append(f"{heading}\n{content}")
        else:
            parts.append(heading)

    return "\n\n".join(parts)


def extract_heuristic_notes(transcript: str) -> str:
    """Simple pattern-based extraction as fallback when Ollama is unavailable."""
    sections: dict[str, list[str]] = {
        "## Key Concepts": [],
        "## Definitions": [],
        "## Examples": [],
        "## Action Items / Deadlines": [],
        "## Questions Raised": [],
    }

    sentences = [s.strip() for s in re.split(r"[.!?]+", transcript) if len(s.strip()) > 15]

    for sentence in sentences:
        sl = sentence.lower()
        if re.search(r"\b(is defined as|means|refers to|is called)\b", sl):
            sections["## Definitions"].append(f"- {sentence}")
        elif re.search(r"\b(for example|such as|for instance|e\.g\.)\b", sl):
            sections["## Examples"].append(f"- {sentence}")
        elif re.search(r"\b(assignment|homework|due|deadline|exam|quiz|submit)\b", sl):
            sections["## Action Items / Deadlines"].append(f"- {sentence}")
        elif re.search(r"\b(why|how does|what is|when does)\b.*\?", sl):
            sections["## Questions Raised"].append(f"- {sentence}")

    parts = []
    for heading, bullets in sections.items():
        if bullets:
            parts.append(f"{heading}\n" + "\n".join(bullets[:8]))

    return "\n\n".join(parts)


async def generate_notes_for_session(
    db: AsyncSession,
    session_id: str,
    broadcast_callback=None,
) -> NotesVersion | None:
    """Run one notes pass for a session and store it as a new version.

    Reads segments newer than ``last_summarized_segment_id``, extracts notes
    from that window, merges them into the previous version, saves the
    result and (optionally) broadcasts it to the browser. Returns the new
    ``NotesVersion`` or ``None`` when there was nothing new.
    """
    session_result = await db.execute(select(Session).where(Session.id == session_id))
    session = session_result.scalar_one_or_none()
    if not session:
        logger.warning(f"Session {session_id} not found")
        return None

    query = select(TranscriptSegment).where(TranscriptSegment.session_id == session_id)
    if session.last_summarized_segment_id:
        last_segment_result = await db.execute(
            select(TranscriptSegment).where(
                TranscriptSegment.id == session.last_summarized_segment_id
            )
        )
        last_segment = last_segment_result.scalar_one_or_none()
        if last_segment:
            query = query.where(TranscriptSegment.created_at > last_segment.created_at)

    query = query.order_by(TranscriptSegment.chunk_index, TranscriptSegment.ts_start)
    segments_result = await db.execute(query)
    segments = segments_result.scalars().all()

    if not segments:
        logger.info(f"No new segments for session {session_id}")
        return None

    # Cap the transcript sent to the model — enough context without overwhelming it
    new_transcript = " ".join([seg.text for seg in segments])[-3000:]

    latest_notes_result = await db.execute(
        select(NotesVersion)
        .where(NotesVersion.session_id == session_id)
        .order_by(NotesVersion.version.desc())
        .limit(1)
    )
    latest_notes = latest_notes_result.scalar_one_or_none()
    current_notes = latest_notes.notes_md if latest_notes else ""

    ollama_available = await check_ollama_available()

    if ollama_available:
        logger.info(
            f"Extracting notes with Ollama ({settings.ollama_model}) for session {session_id}"
        )
        extracted = await extract_notes_with_ollama(new_transcript)
        if extracted:
            notes_md = merge_notes(current_notes, extracted)
        else:
            notes_md = merge_notes(current_notes, extract_heuristic_notes(new_transcript))
    else:
        logger.info(f"Ollama unavailable, using heuristics for session {session_id}")
        notes_md = merge_notes(current_notes, extract_heuristic_notes(new_transcript))

    new_version = (latest_notes.version + 1) if latest_notes else 1

    notes_version = NotesVersion(
        session_id=session_id,
        version=new_version,
        notes_md=notes_md,
    )
    db.add(notes_version)

    session.last_notes_version = new_version
    session.last_summarized_segment_id = segments[-1].id

    await db.commit()
    await db.refresh(notes_version)

    logger.info(f"Created notes version {new_version} for session {session_id}")

    if broadcast_callback:
        await broadcast_callback(
            session_id,
            {
                "type": "notes_update",
                "notes_md": notes_md,
                "version": new_version,
            },
        )

    return notes_version
